### ISSUE TITLE
golint warnings

### ISSUE THREAD

**Issue by oneumyvakin** [ababo/mastore#2]
It'll be nice to fix golint warnings https://goreportcard.com/report/github.com/ababo/mastore :

config.go:3: exported type Config should have comment or be unexported 
read.go:131: exported type ReadFunc should have comment or be unexported 
read.go:133: exported method Store.FindValues should have comment or be unexported 
read.go:198: exported method Store.FindKeys should have comment or be unexported 
store.go:7: exported type Store should have comment or be unexported 
store.go:9: don't use underscores in Go names; struct field log_ should be log 
store.go:16: exported function New should have comment or be unexported 
store.go:16: don't use underscores in Go names; func parameter log_ should be log 
write.go:14: exported method Store.AddValue should have comment or be unexported 
write.go:41: exported method Store.Flush should have comment or be unexported

**Comment by ababo** [comment]
Fixed in 3b88efaac51f7ce741cfd5ebb92ce70de2837c39.
